name: Deploy Laravel to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, bcmath, zip, intl, gd

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user   # ⚠️ ghi thẳng luôn cho chắc
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/blulavelle

            git fetch origin
            git reset --hard origin/main

            composer install --no-dev --optimize-autoloader --no-interaction

            php artisan migrate --force
            php artisan config:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize
            
            sudo chown -R nginx:nginx storage bootstrap/cache
            sudo chmod -R 775 storage bootstrap/cache
            
            sudo systemctl restart php-fpm
            sudo systemctl restart nginx